image: java:11

stages:
  - build
  - docker-build
  - docker-push
  - docker-deploy-swarm

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - build/libs/socshared-storage-service-1.0.0-SNAPSHOT.jar

docker-build:
  stage: docker-build
  script:
    - docker 2>/dev/null 1>&2 rmi `docker images -aq` || true
    - docker build -t $CI_DOCKER_LOGIN/socshared-storage-service .

docker-push:
  stage: docker-push
  script:
    - docker login -u "$CI_DOCKER_LOGIN" -p "$CI_DOCKER_PASSWORD"
    - docker push $CI_DOCKER_LOGIN/socshared-storage-service

docker-deploy-swarm:
  stage: docker-deploy-swarm
  script:
    - touch .env_storage
    - echo "SPRING_PROFILE=dev" >> .env_storage
    - echo "POSTGRES_HOST=storage_postgres_db" >> .env_storage
    - echo "POSTGRES_USER=admin" >> .env_storage
    - echo "POSTGRES_PASSWORD=admin" >> .env_storage
    - echo "POSTGRES_DB=storage" >> .env_storage
    - echo "AUTH_SERVICE=auth_service" >> .env_storage
    - docker stack deploy -c docker-compose.yaml socshared
