spring:
  datasource:
    url: jdbc:h2:mem:facebook_db?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: https://zipkin.socshared.ml/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq.socshared.ml} # RabbitMQ host.
    password: ${RABBIT_PASS:admin} # Login to authenticate against the broker.
    port: ${RABBIT_PORT:5672} # RabbitMQ port.
    username: ${RABBIT_USER:admin} # Login user to authenticate to the broker.

feign:
  url:
    auth: ${AUTH_SERVICE:https://auth.socshared.ml}

management:
  endpoints:
    web:
      exposure:
        include: auditevents, beans, caches, conditions, configprops, health, httptrace, info, loggers, metrics, mappings, shutdown