spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/storage
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: create-drop
  zipkin:
    base-url: http://zipkin/
    service:
      name: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true

feign:
  url:
    mail: ${AUTH_SERVICe:https://auth.socshared.ml}